version: '3'

services:
  yarn:
    build:
      context: ./env/docker/yarn
      dockerfile: yarn
    command: "/bin/true"
    volumes:
    - .:/app

  event-engine-cockpit:
    build:
      context: .
      dockerfile: env/docker/nginx/event-engine-cockpit
    ports:
      - "3001:443"
