on:
  release:
    types: [published]

name: "Build And Push Docker"

jobs:
  build-and-push-docker:
    name: "Build And Push Docker"

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - name: "Install dependencies"
      run: docker-compose run --rm yarn yarn install

    - name: "Build event-engine-cockpit"
      run: docker-compose run --rm yarn yarn build

    - name: "Build image"
      run: docker-compose build event-engine-cockpit

    - name: "Login Docker Hub"
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

    - name: "Tag image"
      run: "docker tag $(docker images | grep -E '^cockpit_event-engine-cockpit.*latest' | awk -e '{print $3}') proophsoftware/event-engine-cockpit:$(echo ${GITHUB_REF##*/} | sed -e 's/v//')"

    - name: "Tag as latest"
      run: "docker tag $(docker images | grep -E '^cockpit_event-engine-cockpit.*latest' | awk -e '{print $3}') proophsoftware/event-engine-cockpit:latest"

    - name: "Push image"
      run: "docker push proophsoftware/event-engine-cockpit:$(echo ${GITHUB_REF##*/} | sed -e 's/v//')"

    - name: "Push latest image"
      run: "docker push proophsoftware/event-engine-cockpit:latest"

    - name: "Cleanup"
      run: rm /home/runner/.docker/config.json

